version: '3.1'
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=if_sul_minas
            - MYSQL_USER=user
            - MYSQL_PASSWORD=123456
        ports:
            - '3306:3306'